### ISSUE TITLE
Using this in DHCP cookbook

### ISSUE THREAD

**Issue by jmccann** [zuazo/kitchen-travis-example-cookbook#1]
@zuazo Thanks a ton for this!  I started trying to figure out how to do this (test-kitchen in TravisCI using docker) myself using examples from rocker (https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml) and other misc examples I found online.  But your repo wraps it all up and was cleaner/simpler!

Thanks a ton!  Using this in https://github.com/chef-brigade/dhcp-cookbook

**Comment by zuazo** [comment]
Yes, many of these scripts need some minor tweaks to work with kitchen, such as setting the local port range.

I copied almost everything from this repository: [zuazo/docker-in-travis](https://github.com/zuazo/docker-in-travis), which has an [acknowledgments](https://github.com/zuazo/docker-in-travis#acknowledgements) section with many links 

Anyway, thanks for your feedback :smiley: I added your cookbook to the README and a link to the acknowledgments.
