### ISSUE TITLE
/etc/apparmor.d/abstractions/lxc/container-base issue

### ISSUE THREAD

**Issue by steenzout** [zuazo/kitchen-travis-example-cookbook#2]
I was testing your repo on travis-ci and the build job got stuck at this point:

```
Installing new version of config file /etc/bash_completion.d/lxc ...
Configuration file '/etc/apparmor.d/abstractions/lxc/container-base'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** container-base (Y/I/N/O/D/Z) [default=N] ? 
```

example: https://travis-ci.org/saucelabs-ansible/packer/jobs/134279269

any ideas?

**Comment by steenzout** [comment]
I'm testing a PR and I'll send a patch if I manage to get this fixed.

**Comment by zuazo** [comment]
@steenzout thanks for the report!

I would try adding `-o Dpkg::Options::=--force-confnew` to the [`apt-get install lxc`](https://github.com/zuazo/kitchen-in-travis/blob/5fc753a5a0d13eb5d099103e78918b6f497b60ba/scripts/start_docker.sh#L100).

Maybe we should pass that argument to all the _apt-get install_s.

**Comment by steenzout** [comment]
I did that and worked.
I'll post PR tomorrow.

**Comment by steenzout** [comment]
@zuazo I noticed that [travis-ci](https://travis-ci.org/) now provides a `docker` service so I'm wondering if you still need the `docker_start.sh` file.

**Comment by zuazo** [comment]
No, you don't. See here: https://github.com/zuazo/kitchen-in-travis-native

**Comment by typekpb** [comment]
@zuazo thanks a lot for idea with: `-o Dpkg::Options::=--force-confnew`, it works also seamlessly for me once used with `apt-get upgrade -yy` as well as with `apt-get dist-upgrade -yy`

**Comment by zuazo** [comment]
You are welcome, @typekpb :wink:

You can use `dpkg --force-help` to see some of those configuration options documentation:

```
[...]
  [!] confnew            Always use the new config files, don't prompt
  [!] confold            Always use the old config files, don't prompt
  [!] confdef            Use the default option for new config files if one
                         is available, don't prompt. If no default can be found,
                         you will be prompted unless one of the confold or
                         confnew options is also given
  [!] confmiss           Always install missing config files
  [!] confask            Offer to replace config files with no new versions
[...]
```
